# Generated by Django 3.1.3 on 2020-11-13 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_number', models.BigIntegerField(blank=True, null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('member_type', models.CharField(blank=True, choices=[('S', 'Student'), ('C', 'Community Member')], max_length=1, null=True)),
                ('is_e_board', models.BooleanField(default=False)),
                ('cr2_cleared', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShowSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_on', models.TimeField()),
                ('time_off', models.TimeField()),
                ('day_of_week', models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('R', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday'), ('U', 'Sunday')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='StationService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('DJ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj.dj')),
            ],
        ),
        migrations.AddField(
            model_name='dj',
            name='availibility',
            field=models.ManyToManyField(blank=True, related_name='availibility', to='dj.ShowSlot'),
        ),
        migrations.AddField(
            model_name='dj',
            name='preferred_shows',
            field=models.ManyToManyField(blank=True, related_name='preferred_shows', to='dj.ShowSlot'),
        ),
        migrations.AddField(
            model_name='dj',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Clearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('valid_until', models.DateField()),
                ('DJ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj.dj')),
            ],
        ),
    ]
